Superclass without empty constructor precondition
spgroup/SMATransf pull request #1
Opened 2022-08-09 01:21 UTC by ToniMaciel

2022-08-10 18:40 UTC, pauloborba approved these changes

2022-08-10 18:40 UTC, pauloborba commented on src/main/java/org/Transformations.java
> +    private static boolean superclassWithoutEmptyConstructor(TypeDeclaration node) {
superclassesWithoutEmptyConstructor retrataria melhor o que esse método faz? já que ele parece verificar se todas as superclasses (imediatas ou não) não tem construtor vazio

2022-08-12 01:05 UTC, ToniMaciel commented on src/main/java/org/Transformations.java
> +    private static boolean superclassWithoutEmptyConstructor(TypeDeclaration node) {
Tem razão, Paulo! Dessa forma elucidaria melhor o comportamento do método

2022-09-01 15:20 UTC, leusonmario requested changes

2022-09-01 15:20 UTC, leusonmario commented on src/main/java/org/Transformations.java
> +    private static boolean superclassesWithoutEmptyConstructor(TypeDeclaration node) {
No caso, verifica-se o super class tem um construtor vazio, certo?
E caso a classe esteja em uma hierarquia de herança de nível 3? Por exemplo, A estende B, que estence C.

2022-09-04 15:45 UTC, closed without merging